services:
  zaruma:
    build: .
    container_name: zaruma_gestion
    restart: unless-stopped
    ports:
      - "127.0.0.1:8010:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./pdf:/app/pdf
      - ./uploads:/app/uploads
      - ./static/pdf_header.png:/app/static/pdf_header.png:ro
